_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/ppyolov2_swin_128.yml',
  './_base_/swin_mini_640.yml',
  './_base_/ppyolov2_reader_640.yml',
]

snapshot_epoch: 1
weights: output/ppyolov2_r50vd_dcn_365e_coco/model_final
