_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/ppyolov2_Bot_50_yoloxhead_low_weight.yml',
  './_base_/optimizer_mini.yml',
  './_base_/ppyolov2_reader_640.yml',
]

snapshot_epoch: 1
weights: output/ppyolov2_r50vd_dcn_365e_coco/model_final
