metric: VOC
map_type: 11point
num_classes: 2

TrainDataset:
  !VOCDataSetk
    dataset_dir: dataset/ship_detect
    anno_path: train_list.txt
    label_list: labels.txt
    data_fields: ['image', 'gt_bbox', 'gt_class','difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: dataset/ship_detect
    anno_path: val_list.txt
    label_list: labels.txt
    data_fields: ['image', 'gt_bbox', 'gt_class','difficult']

TestDataset:
  !ImageFolder
    anno_path: dataset/A_test/labels.txt
