epoch: 365

LearningRate:
  base_lr: 0.00075
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 100
    - 200
    - 300
  - !LinearWarmup
    start_factor: 0.
    steps: 200

OptimizerBuilder:
  clip_grad_by_norm: 35.
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
