epoch: 192

LearningRate:
  base_lr: 0.000375
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 1
    - 152
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  clip_grad_by_norm: 35.0
  optimizer:
    type: AdamW
    weight_decay: 0.05
