architecture: YOLOv3
pretrain_weights: prepared_model/convnext_tiny.pdparams
norm_type: sync_bn
use_ema: false
ema_decay: 0.9998

YOLOv3:
  backbone: ConvNeXt
  neck: PPYOLOPAN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

ConvNeXt:
  in_chans: 3
  out_channals: [1,2,3]
  depths: [3, 3, 9, 3]
  dims: [96, 192, 384, 768]
  drop_path_rate: 0.
  layer_scale_init_value: 0.000001

PPYOLOPAN:
  drop_block: true
  block_size: 3
  keep_prob: 0.9
  spp: true

YOLOv3Head:
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv3Loss
  iou_aware: true
  iou_aware_factor: 0.4


YOLOv3Loss:
  ignore_thresh: 0.7
  downsample: [32, 16, 8]
  label_smooth: false
  scale_x_y: 1.05
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss


IouLoss:
  loss_weight: 2.5
  loss_square: true



BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.01
    downsample_ratio: 32
    clip_bbox: true
    scale_x_y: 1.05
  nms:
    name: MatrixNMS
    keep_top_k: 100
    score_threshold: 0.01
    post_threshold: 0.01
    nms_top_k: 10
    background_label: -1
