worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 10
  sample_transforms:
    - Decode: {}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 10}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.027, 0.027, 0.027], std: [0.043, 0.043, 0.043], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6,7,8], [3,4,5], [0,1,2]], anchors: [[10, 13], [16, 30], [33, 23],[30, 61], [62, 45], [59, 119],[116, 90], [156, 198], [373, 326]], downsample_ratios: [32, 16, 8]}
  batch_size: 2
  shuffle: true
  drop_last: true
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [768,768], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.027, 0.027, 0.027], std: [0.043, 0.043, 0.043], is_scale: True}
    - Permute: {}
  batch_size: 4

TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}                                                                     