epoch: 192

LearningRate:
  base_lr: 0.0000375
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 153
    - 173
  - !LinearWarmup
    start_factor: 0
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

